"""add_source_and_is_transfer_to_transactions

Revision ID: 3709cda12d1e
Revises: a1b2c3d4e5f6
Create Date: 2026-07-30 22:28:25.720283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3709cda12d1e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statement_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_uploads_id'), 'statement_uploads', ['id'], unique=False)
    op.add_column('transactions', sa.Column('source', sa.String(length=20), nullable=False))
    op.add_column('transactions', sa.Column('is_transfer', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_transfer')
    op.drop_column('transactions', 'source')
    op.drop_index(op.f('ix_statement_uploads_id'), table_name='statement_uploads')
    op.drop_table('statement_uploads')
    # ### end Alembic commands ###
